name       : xfce4-panel
version    : 4.18.4
release    : 3
source     :
    - https://archive.xfce.org/src/xfce/xfce4-panel/4.18/xfce4-panel-4.18.4.tar.bz2 : 32304f82094ea3779741f968dc851032d8790eb78f3aa01676520b96cfacfb54
license    : GPL-2.0-or-later
component  : desktop.xfce
summary    : Panel for the Xfce desktop environment.
description: |
    Panel for the Xfce desktop environment.
builddeps  :
    - pkgconfig(exo-2)
    - pkgconfig(garcon-gtk3-1)
    - pkgconfig(libxfce4ui-2)
    - pkgconfig(libwnck-3.0)
setup      : |
    %configure \
        --sysconfdir=/usr/share
build      : |
    %make
install    : |
    %make_install
